import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-200 min-h-screen`}>
        <main className="container px-80 py-16 mx-auto ">{children}</main>
      </body>
    </html>
  );
}
